import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Next Movies",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="p-4">
					<Header />
					<section className="flex gap-4">
						<Sidebar />
						<main className="pl-4 border-l">{children}</main>
					</section>

                    <footer className="text-xs py-4 mt-4 border-t text-gray-600 text-center">
                        &copy; Copyright 2024
                    </footer>
				</div>
			</body>
		</html>
	);
}
